

# .streamlit/secrets.toml

#https://docs.google.com/spreadsheets/d/19_k42-5uheady1MU-1o84xzyXnGqB4V0X35htbL_Enw/edit?usp=sharing

#public_gsheets_url = "https://docs.google.com/spreadsheets/d/xxxxxxx/edit#gid=0"

public_gsheets_url = "https://docs.google.com/spreadsheets/d/19_k42-5uheady1MU-1o84xzyXnGqB4V0X35htbL_Enw/edit#gid=0"